apiVersion: v1
kind: Service
metadata:
    name: agh
    namespace: default
spec:
    ports:
        - port: 80
          targetPort: 80
    clusterIP: None
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWDQ3QVNwNm4xeW8ydzdl
            RjJLVmIwUTEzcHV1TWxiaHByNm41RHY0dFJRCkl5YnJLWGRZcnA4bXNPRFh5Uk5N
            OSs4K21tamp0YUNzKzVWZndiWTRmT1UKLS0tIGVmMmhBS1FqclVjL3Uyd1pGamJa
            d0lpdW1BVWQwSmZpM3lGK2ZKb0RjaEEKjzDm4tR92VnyAJDKUv2igiskpFCFvxC2
            u7MqyrtP1XoGsWnyE0V2Oqm15SoOMSh6aSIFc+FxN7LRfSqtzsvhHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T19:20:13Z"
    mac: ENC[AES256_GCM,data:/Pt07Ft4K99pviD9JUXIY986fsQ4xsp6Qybpc0nAoUtMcHCsPGqsZCKB4A2T7k/sRYRQVR931ihrUNl6ITLPNQhTZO2pE25R3v/kjM1qmP+B+oaPGSJSRQ78PYnhmGXxHGJVtepThcPRXTq09ztywe4H6OJEHeoc1C+IfNW8TGU=,iv:+WSG1ECrnsGiqoTRdAfh+B4+/NxaYCosmgZ4xTkMnkA=,tag:oE5EYWWrICanX0sL9HtpbQ==,type:str]
    pgp: []
    encrypted_regex: ^(gethomepage.dev/widget.password)$
    version: 3.9.0
---
apiVersion: v1
kind: Endpoints
metadata:
    name: agh
    namespace: default
subsets:
    - addresses:
        - ip: 10.10.10.231
      ports:
        - port: 80
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWDQ3QVNwNm4xeW8ydzdl
            RjJLVmIwUTEzcHV1TWxiaHByNm41RHY0dFJRCkl5YnJLWGRZcnA4bXNPRFh5Uk5N
            OSs4K21tamp0YUNzKzVWZndiWTRmT1UKLS0tIGVmMmhBS1FqclVjL3Uyd1pGamJa
            d0lpdW1BVWQwSmZpM3lGK2ZKb0RjaEEKjzDm4tR92VnyAJDKUv2igiskpFCFvxC2
            u7MqyrtP1XoGsWnyE0V2Oqm15SoOMSh6aSIFc+FxN7LRfSqtzsvhHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T19:20:13Z"
    mac: ENC[AES256_GCM,data:/Pt07Ft4K99pviD9JUXIY986fsQ4xsp6Qybpc0nAoUtMcHCsPGqsZCKB4A2T7k/sRYRQVR931ihrUNl6ITLPNQhTZO2pE25R3v/kjM1qmP+B+oaPGSJSRQ78PYnhmGXxHGJVtepThcPRXTq09ztywe4H6OJEHeoc1C+IfNW8TGU=,iv:+WSG1ECrnsGiqoTRdAfh+B4+/NxaYCosmgZ4xTkMnkA=,tag:oE5EYWWrICanX0sL9HtpbQ==,type:str]
    pgp: []
    encrypted_regex: ^(gethomepage.dev/widget.password)$
    version: 3.9.0
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: agh
    namespace: default
    annotations:
        gethomepage.dev/href: https://agh.d90.name
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Network
        gethomepage.dev/icon: adguard-home
        gethomepage.dev/name: adguard
        gethomepage.dev/widget.type: adguard
        gethomepage.dev/widget.url: https://agh.d90.name
        gethomepage.dev/widget.username: d90
        gethomepage.dev/widget.password: ENC[AES256_GCM,data:f5IndJPrk9oLbPUJFzJLJkqAEM4=,iv:PwrsH7SNm7xyo1j6w1uvX9eEGlpWQDTs1J11qjMIzI0=,tag:PbA27FOMCY9umEzEXFdwXg==,type:str]
spec:
    entryPoints:
        - websecure
    routes:
        - match: Host(`agh.d90.name`)
          kind: Rule
          services:
            - name: agh
              port: 80
    tls:
        secretName: tls.agh
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWDQ3QVNwNm4xeW8ydzdl
            RjJLVmIwUTEzcHV1TWxiaHByNm41RHY0dFJRCkl5YnJLWGRZcnA4bXNPRFh5Uk5N
            OSs4K21tamp0YUNzKzVWZndiWTRmT1UKLS0tIGVmMmhBS1FqclVjL3Uyd1pGamJa
            d0lpdW1BVWQwSmZpM3lGK2ZKb0RjaEEKjzDm4tR92VnyAJDKUv2igiskpFCFvxC2
            u7MqyrtP1XoGsWnyE0V2Oqm15SoOMSh6aSIFc+FxN7LRfSqtzsvhHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T19:20:13Z"
    mac: ENC[AES256_GCM,data:/Pt07Ft4K99pviD9JUXIY986fsQ4xsp6Qybpc0nAoUtMcHCsPGqsZCKB4A2T7k/sRYRQVR931ihrUNl6ITLPNQhTZO2pE25R3v/kjM1qmP+B+oaPGSJSRQ78PYnhmGXxHGJVtepThcPRXTq09ztywe4H6OJEHeoc1C+IfNW8TGU=,iv:+WSG1ECrnsGiqoTRdAfh+B4+/NxaYCosmgZ4xTkMnkA=,tag:oE5EYWWrICanX0sL9HtpbQ==,type:str]
    pgp: []
    encrypted_regex: ^(gethomepage.dev/widget.password)$
    version: 3.9.0
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: tls.agh
    namespace: default
spec:
    dnsNames:
        - agh.d90.name
    secretName: tls.agh
    privateKey:
        algorithm: ECDSA
        size: 256
    revisionHistoryLimit: 1
    issuerRef:
        name: le-prod-issuer
        kind: ClusterIssuer
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWDQ3QVNwNm4xeW8ydzdl
            RjJLVmIwUTEzcHV1TWxiaHByNm41RHY0dFJRCkl5YnJLWGRZcnA4bXNPRFh5Uk5N
            OSs4K21tamp0YUNzKzVWZndiWTRmT1UKLS0tIGVmMmhBS1FqclVjL3Uyd1pGamJa
            d0lpdW1BVWQwSmZpM3lGK2ZKb0RjaEEKjzDm4tR92VnyAJDKUv2igiskpFCFvxC2
            u7MqyrtP1XoGsWnyE0V2Oqm15SoOMSh6aSIFc+FxN7LRfSqtzsvhHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T19:20:13Z"
    mac: ENC[AES256_GCM,data:/Pt07Ft4K99pviD9JUXIY986fsQ4xsp6Qybpc0nAoUtMcHCsPGqsZCKB4A2T7k/sRYRQVR931ihrUNl6ITLPNQhTZO2pE25R3v/kjM1qmP+B+oaPGSJSRQ78PYnhmGXxHGJVtepThcPRXTq09ztywe4H6OJEHeoc1C+IfNW8TGU=,iv:+WSG1ECrnsGiqoTRdAfh+B4+/NxaYCosmgZ4xTkMnkA=,tag:oE5EYWWrICanX0sL9HtpbQ==,type:str]
    pgp: []
    encrypted_regex: ^(gethomepage.dev/widget.password)$
    version: 3.9.0
