apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - tls.yaml
  # - middlewares
  - service.yaml
  - serverstransport
  # routers are applied by the apps Flux Kustomization after Traefik CRDs are ready
