apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble
  namespace: kube-system
  annotations:
    gethomepage.dev/href: "https://hubble.d90.name"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Cilium network flow observability
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: cilium.png
    gethomepage.dev/name: Hubble
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hubble.d90.name`)
      kind: Rule
      services:
        - name: hubble-ui
          kind: Service
          port: 80
  tls:
    secretName: tls.hubble
