apiVersion: batch/v1
kind: CronJob
metadata:
  name: route53-dyndns-cron
  namespace: default
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - image: docker.io/bshaw/route53-dyndns:5@sha256:cb39cda191ef956fdc873b92b9d460cb3c4dbadb255d6528c705c0dcb2d2c9ca
            name: route53-dyndns
            imagePullPolicy: Always
            envFrom:
            - prefix: ''
              secretRef:
                name: route53-dyndns-secret
            args:
            - --record
            - home.nickdininno.com
            - --verbose
          restartPolicy: OnFailure