apiVersion: batch/v1
kind: CronJob
metadata:
  name: route53-dyndns-cron
  namespace: default
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - image: docker.io/bshaw/route53-dyndns:5@sha256:e2990a3e7ace32eeffbf183d77be9a95374769c438c156eeb444c7db79e1b0b4
            name: route53-dyndns
            imagePullPolicy: Always
            envFrom:
            - prefix: ''
              secretRef:
                name: route53-dyndns-secret
            args:
            - --record
            - home.nickdininno.com
            - --verbose
          restartPolicy: OnFailure