apiVersion: batch/v1
kind: CronJob
metadata:
  name: route53-dyndns-cron
  namespace: default
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - image: docker.io/bshaw/route53-dyndns:5@sha256:e878dccb9c8a0b3ce69318160555414e7000649a1b84f20c88a70a1cc7eb629c
            name: route53-dyndns
            imagePullPolicy: Always
            envFrom:
            - prefix: ''
              secretRef:
                name: route53-dyndns-secret
            args:
            - --record
            - home.nickdininno.com
            - --verbose
          restartPolicy: OnFailure