apiVersion: v1
kind: Secret
metadata:
    name: route53-dyndns-secret
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Pyc1CeUgvMMHvLFjslkO+4mRrrI=,iv:OZf4gBNBp0qWwR4hbS92HWtSE0MeMeHoyei+J3i5+Hc=,tag:fbnjLhql7CABrQXhXKC2IQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Xr8QEs6DOK4FIW38TsX96/ToX+YwA4lD1XwayAuzmtf2tYpEcIAm2g==,iv:aS9U0/8cdSy5g/fhhT9uznZG9lUthENYY7dQFY7H664=,tag:4Ud0WO12kR8DAdVjvFgMaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYnE5WWw0eVVNRHFlcVJM
            cEZkZEh6NkxKTXZYcFhIWEFGVlRJNjhJS2xJCnBMbUc3aU9QbnEzaDZralRiQ0N4
            SFdXbXR5VERxZzdyT0NRVTd4S3NMRFkKLS0tIFppaVFjMnI1NW9jSWk2dXYyemto
            TGxUVkZkWXZiNXJWZk8wZ04xT1d1c3cKkWHV7PJIrEaZRG4Cy/FV+in7srgO5ism
            dlu4lhc1gPx0HsMyXUtNcsrE6XZ3Wvhsr6RkWhS/msWx+pFTxXpETg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T13:38:12Z"
    mac: ENC[AES256_GCM,data:A6rI7GepbBf8CvArRjPXa6s4RqyBRnXShT4nPH14Oc4HewbRGbnh0gm++lACINqHgKEkFBAxapQrMWB7Z6WfiAUaTedeZ/igrpaGpCQ5kpq2pcjEuGpp3ZeHzympoO0m32HkVs6frDq6EGhSaGO0SGP/tGtrs2Oe0xsl3MDOrAQ=,iv:pOOALOBfoLzKKzKKCdXh63b0hf1k/WUsM1USZAt6v1w=,tag:RGmlcPqcOwJV4UZWfa4koA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3