apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls.hubble
  namespace: kube-system
spec:
  dnsNames:
    - hubble.d90.name
  secretName: tls.hubble
  privateKey:
    algorithm: ECDSA
    size: 256
  revisionHistoryLimit: 1
  issuerRef:
    name: le-prod-issuer
    kind: ClusterIssuer
