apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bazarr-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  storage:
    storageClass: nfs-client
    size: 1Gi
  bootstrap:
    initdb:
      database: bazarr
      owner: bazarr
      secret:
        name: bazarr-postgres-secret
  superuserSecret:
    name: bazarr-postgres-secret
  monitoring:
    enablePodMonitor: true