apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bazarr-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:VJfw5VVu,iv:Fqzcas8P4d3VlpqtB9+zSEEXFrKj0QKYKQZLcLmmCWM=,tag:+DRIMcjNTACZdvSj3zPRvw==,type:str]
    password: ENC[AES256_GCM,data:xWdOgNNz4tKANg5gTUMCBWCkvfU=,iv:nMCQf/fjaJ2Kfd99nW8Xz4CEzE2jZk6eW9I8cOzS3v8=,tag:QwJ6htI3h8YstJV8ZvUAWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z2pjVGxEMCtQN1NKZ1pW
            ZXJ6OThhQ1d5eStsK1F0SHZmak5YSmFyZlVrCm91d1ZUUzVkYm1ZaGphZlZBRlNU
            cXhibC9LTTcwYk80SmJ1ZXgrMzJGRE0KLS0tIFFyZHVXWmVuRWkyREZTTlFBZElZ
            bk5heXhkYzFhcU0vRHNRenlxR1Q2ek0KUVQf6Z0XqKdOFG5RAvQvoG3pnAAT8Ipf
            SkLKKHQwWbxHxwL7KPD2a6Mlx4qE70A8WOFBDgDI12aGgMMG3EQdnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T03:26:44Z"
    mac: ENC[AES256_GCM,data:OPVgYkLPSz17clbUcLWgOCbpvSv3dH+NUYaHc90ihOpTRdbmjZHcc6Oo2eydbIpTycA3Ln13rW4fRupxQGLqQ73Dsu+HGVER4+c/ODk2CLwBLG/9Zcic40Y1mZZx5zyaTjKYNZ3z01P3yGmHJhia/RETwyc21UbN0KOKnMthTr8=,iv:ehZ2QCXLc9RuZGUPO5KWci4o1TNqodcGnSylhi+k5YA=,tag:kuouAh0p5BYCUL/FG3BAnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0