apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: bazarr-secret
    namespace: default
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rGjDxQmXV+YhN+BelRgb8hqxhI0=,iv:vACAC3yIYMOO6ybrysqov0SSRMViXKCzSsWInyqlnhg=,tag:N8hH182g5DE3qc4owS/Hmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K0djdXNsZEg4VVFTZjJq
            WmlBNHZrRWZNd2QyRjRoOTAxTFg5TXlkckRNCnVHSWV0Qm9CUW5MeWovN3hrUTlD
            K2JYdithT3NRazZSU0xPKzNLNFhLWUkKLS0tIDR4N1haMENQcTk5aC8zOThuODM5
            UExTVXk1REpBOG00V3pOd21qajZsTHcK8kB8Y50L1mMGady822RzfKQZi87V4v76
            ItbykoiL48zmY+SFXBkZpNrFhysVhWu0jPRgHhmiF1IX+hYMnVkT1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T04:29:13Z"
    mac: ENC[AES256_GCM,data:CoSUzu5+/ssScoja/1WEXxZ8kXd1uzvjSF/KtoEIkUV23yfRVYY+svrv7gcQGLZDMKur+ciydLPow0ZLTT+3PUMkAC/+MNLdz8Qs4kwUoGt/JCEG1axLFg3E15lPxeGDzUqmvBbF6jKMB9uJij0yEnn1du5x2BTSroTS6WJlLxE=,iv:2GAqdAlRFLj2onoaro9Wug07pVB3JLrKH4Rl3+chWnk=,tag:2JaQvcoTbyvx8lT3w2Sbdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0