apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls.bazarr
  namespace: default
spec:
  dnsNames:
    - bazarr.d90.name
  secretName: tls.bazarr
  privateKey:
    algorithm: ECDSA
    size: 256
  revisionHistoryLimit: 1
  issuerRef:
    name: le-prod-issuer
    kind: ClusterIssuer
