apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: containerdata-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: "10.10.10.210"     # Your NAS address
  share: "/containerData"            # The exported path on your NAS   
reclaimPolicy: Retain
volumeBindingMode: Immediate
