apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - tdarr
  - containerData-sc.yaml
  - data-sc.yaml
  - helmrelease-csi-nfs.yaml
  - helmrelease-nfs-ext-provisioner.yaml
  - storageClass-nfs.yaml
  