apiVersion: v1
kind: ServiceAccount
metadata:
  name: talos-dns-opnsense
  namespace: talos-dns-opnsense
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talos-dns-opnsense
rules:
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: talos-dns-opnsense
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: talos-dns-opnsense
subjects:
  - kind: ServiceAccount
    name: talos-dns-opnsense
    namespace: talos-dns-opnsense
