apiVersion: v1
kind: Secret
metadata:
    name: opnsense-creds
    namespace: talos-dns-opnsense
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:OKPgFCNELv++A+CcfiaIXCaPAQb2cm8VFXZSaOKc16YNYH+jdMd00tU4eZ0Iww/be1jwZ5jnMkpOW6TG9HRdCvVdChsYlemPcOX3kcq5umg=,iv:N6c0Ed8vZu1DJSHMh7Kzqa0Mjp0gK/zOkiCBihSCxSw=,tag:VzJuqTre499UxFJC7hO8Rg==,type:str]
    api-secret: ENC[AES256_GCM,data:OWg4i0AlvAmYG2Z5c5lbgO6hwwvdgHhUh0YYAZZEQkTuli3EJaOCiDnE9zPxfBWRxUZ02y9uQm3RyTRlIvixljSWa20xC6+s+18NUDhqKgI=,iv:Yx6Nc8sFYZtSazHsoLoiSfYcyL+UesgPs6KNmQkOcIc=,tag:/iT795Wgc9rObP8y1YFFVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZy94K3FEWE5MbGVLNmhp
            TTNYZ041b0kxRHJMYlVwSWFnMDZoVU5yTGtzCjkzYTZRVFA3SW1HZHczSS8rTGtK
            WDkwSzBlRFBQTVhjd1phSDVvcXY2aWsKLS0tIERMWXFuRDlpQVdDczZCQ3ppRXU4
            WXBMbzJBTk9raVN2WXpGVHlQK0pSZWsKz7hkaBAdHUeLdN0USjnXuQZiPDRCIR7z
            nZCIpI9NnmdqoS3W9KHItmIFJM6Ktc+eyrXbnDwwGHzKeP7kvMF2ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T15:37:44Z"
    mac: ENC[AES256_GCM,data:l+zfuq68xc/uAEUVrL+kBxcrGUUieSbQ8jiPGsO2bXchJKgYRoFssEJFCr1BjnlQOdMMdt4SFhJlwTC3+G2E2Dase3J8Nthydc1c9CzsPJzgwZ7CMiBkwuMvpXAO77kWHabticR+NdxENLSTW8+bvIsZCiUwOwoeCgYAQ9Wqai8=,iv:45VOnV91eONzllWNSsASsx0HE+0tPSAl0ZZIlYb4oAs=,tag:7AiEeRVyxuKt/KGdPws+bQ==,type:str]
    pgp: []
    encrypted_regex: ^(api-key|api-secret)$
    version: 3.9.0
