apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    PUBLIC_SECRET_DOMAIN: ENC[AES256_GCM,data:a4qJ5HfrwtGCX2eEFRVt,iv:7EceEo1diw5zFuiZkMvwylYksAWE/p81U3OTgffR1Vc=,tag:qWb+G0UP74a7BqGy9Fok6A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:K8vhvQLEDSY=,iv:woS5zfLs0EkYuL4VsHegs9d0p/jmr1rpSJ1a8Um8qc0=,tag:3r3AtdxN5ytb4dHzrqwpBg==,type:str]
    NAS_NAME: ENC[AES256_GCM,data:wluw,iv:zlaDRMN+N3AT3h/xXHpSt2YiuUCAs4rTwPYVeKdZmoQ=,tag:8JRU7lMibDY+ybY8r1NQjA==,type:str]
    NAS_IP: ENC[AES256_GCM,data:zFoQPxehYQk8cQIp,iv:WjPKgfoPpvJ/3QWTVy7mFOWR7/vayKtA+dvxEhAyAKY=,tag:gNMSz0pS240hZm6BbH8Dmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb080M0pOa2d0TzVOM0Jo
            ckh0Q0JhL0lTVWNsbnVRTm41NmJXYXFBcnpVClNpYU80Vk5zWkw4Y1FWbDBrb2dP
            QnRGNVVRZHI4aDc4b3BKVVlnYXR6VXMKLS0tIEtMYVRleGZkOUVKRDEwQlBGRjFV
            Y3VkYjRtbC92NHFqKzV2OGp3dVZEMDQKc3IQMkoXHJnrj5uG7vMUQceqwatZqOcY
            uIBZ+ea+Z9bCfUiaWDEdNwiqG2pyRsrMDxIvFULgEc8kjxKCu5Wn+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T15:49:07Z"
    mac: ENC[AES256_GCM,data:9l/hdIgawPa10X+i87rPx2Tvroiu4pwtmm6g/i4OcZxYlfZFsolNtCRR6lso0QvaL/2QaoVB6aJtaUw+d1KLMRyDpdlozIugZs1PDZPjV1BQgAqua3l5iE9rDsiGPoSnD8zu15yEwQKJXp1qvySD8wmg+2ILBaZb5AZHtEWBdUA=,iv:OuFvFKA8nqZMyy+nTmtgmgzOtrMbulR0OIzXQkf5w3k=,tag:C+m+aBLd9OL+Z63eFxQ1iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3