apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: peptide-pitstop-secret
    namespace: default
stringData:
    PT_FIELD_KEY: ENC[AES256_GCM,data:ojRFk7+pM/bbqOg6DvmokWThLNEBf37ebjbd5mKxKEPUF9uIUdsI21Hu44A=,iv:FQRlQrfn4uDmNePBXCbLX0ZNXlctMLSr2E/EwKPRP9c=,tag:bKL1Ynp5T4P40QN7L4mHcQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:uS0oxCEI2M6+IRyZ9j/qstE4zdpGtP6fZ1YWxI968REtYhw//Ffj84ileId98lQdCL0KlERDU/NAQ3rGko3CPQ==,iv:MRvLnU/29jZ58OEwsacDuTQcn7iOsD51DwJ52BATAqE=,tag:vncN7dl9FaNAfSTuilZ0fA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR0pUMDFWeUIwcmg5UUNB
            RG92c3NPRWxVeVZqOEJQbmhMM2Z3UFdHZzE0CjZCYk1ncGwyOXhQOFcvcldJRzVp
            Z1RpN1lqK2hUZTUwZ0VBNWFJL2tkZkkKLS0tIGtTakIvT3d0WXpjMUFkV1UvMG5h
            RDEzM0RLcTlhTHVnK1Z6K0hrNEZoeUEKVtHyFScbFPlUYBdKOEAim85gB40CkLM6
            WdqWK5goHtEr7AvJRgdTFF6YkpazAuu1eSeEni5hcDEVz8dooAOHZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T19:14:30Z"
    mac: ENC[AES256_GCM,data:YgwFQH1xEKnk9Lg8+Ceg0S3Noyifli6ZfWrTFX/ko2EF2HVM8j1g54rEgw9CgYrZbkWQ1AZpGQaSvrMxo6yJMGQJEbwUNyGAfDwhblt+LB2SIx6mpA2I1d55Pj+HKmTu4U1yDFsuzNRsCB+hjmw9kQygt+mtlim/EjHTb//ynSs=,iv:N2YFuJp67j7frqQE3Xk/iFq44//J04BDrlLaRMBXGmU=,tag:MggtwNSmmuOEKxlwarBpFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
