apiVersion: v1
stringData:
    aws_secret_access_key: ENC[AES256_GCM,data:gn+x7yeJmMMpEcP1R+M/S10YSwfQjdbTqlGXoFS7IK7II0q4I8eCMg==,iv:dCm3Se4+REc1GTLqnck11n3cmlcSpwQLz/FdUnijX8k=,tag:sWgCRmlivDRLt0mInyVNzg==,type:str]
kind: Secret
metadata:
    name: aws-secrets
    namespace: cert-manager
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUkh3b1k1VjIzRzdZbUp1
            S3pyWlpZTEhYTTl4SEpoNWtkb1ZoSVlhb0FnCnh6aHRuSGR1WXlEUzJLTTllM2t6
            ci9Xc1FDZEpkNW1ZNnJNTjhBN3RWZW8KLS0tIHNzL0VMSWlVVFlHcnNiZjJpZDFk
            UGhzc045ZUVhVFRoeHdpbmJrUk5VTDQKn1G97jHdB5J9vw1QMs7TCqhSe1Kokbva
            T0DDj743KcAYD/cnOZ8KYOmyKbRuRYRfkV4p9d3BHWOWZMyp7IdMpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-20T22:02:12Z"
    mac: ENC[AES256_GCM,data:MiwsQn3azTq0XUNtaNj5wtTPIXxkRL7R8DHD91mcCqX1YxEoIqGTt0+zGExucBdE0hi2GDVsaq2clzqHXQZmL1uTqgugiXTkLEENHXHSpvcHXBFDOAHdZoSBxFGxFMDz3Ie0QRcRK076o1zk2gVO6EW6RKSnHq1hI4g0xMekM/8=,iv:g7sTNw1qG5XsaRakI6JSS/m7RJIbMFn2vpGAhQhAC2c=,tag:blgpaJ/2MbPBKF9biPe11g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
