apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app scrypted
  annotations:
    {}
  labels:
    app: *app
  namespace: default
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - imagePullPolicy: Always
          name: *app
          volumeMounts:
            - name: nfs-conf
              mountPath: /server/volume
              subPath: scrypted/config
          image: ghcr.io/koush/scrypted:latest@sha256:e78b4fcecdd6c61acaaf22b50ccef303c738da58cc0be57afdb116521df52296
          envFrom:
            - prefix: ''
              configMapRef:
                name: scrypted
                optional: false              
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - name: nfs-conf
          persistentVolumeClaim: 
            claimName: nfs-pvc-containerdata 
  replicas: 1
  # revisionHistoryLimit: 1
  strategy:
    type: Recreate
