apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: media-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:yO4tbTJ5WaQ=,iv:tHfCwGb/zjnMioxrhP5FTkiiwc/2XWNdLlWbEqAt7ys=,tag:WSqCZ32XPqTK49cpHIjrxg==,type:str]
    password: ENC[AES256_GCM,data:vSQaPmDxfQ86d54K,iv:HeqEk8YDuCp5Lv7ToH5XNrtw8ykrSvePrqVB6MYY34g=,tag:B7WhfPRZhNFR8dGht1siSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWGltempVWjNRbDBpaTNU
            YnJzUTVvVVZQakFDTWJwZnV5UTlaYkUrSkJFCjBKV04zdFQ1R2wvcXh2b1B3dVNm
            Z1h3TW9TbW0zTTh2OW5reUFiUU1xQVEKLS0tIFhwazVwWTlGcmtNWU5uSFFqWllu
            OU50dmthbXlnYkRFQ3VIRmdqajZNZVEKberRqZ5MGClIBm4Ml9hXM/o82gTnuBr6
            A4PohhtYuVVnqKw7LusKtXG+z6QklKdk0/OkguytLQ8fWLpLfnS+UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T21:48:42Z"
    mac: ENC[AES256_GCM,data:0nJRXQ9Ax6q6b/2DvI+szOuCelKQH+9ph1fFpVjqfkjrbAi1mwT2TZ1h3olfksyxvShSVXID63WxCH2B+z1GkLsKbmKfigiKrFC0A7L02iUszhzE4nKD77wp/sg1xww52giT1Qo65Rd/wQj+LU9cBBjuOl+mtjZ6YrXfSQ5gCG0=,iv:eVliqO7XZBh0pymqA1GZwD/rbqRHc2A2m0KrPydWEOE=,tag:ARTFvZGh84L1lV4WUQ2eLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0