apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lidarr-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  storage:
    storageClass: nfs-client
    size: 1Gi
  bootstrap:
    initdb:
      database: lidarr
      owner: lidarr
      secret:
        name: lidarr-postgres-secret
      postInitSQL:
        - CREATE DATABASE "lidarr-log" OWNER lidarr;
  superuserSecret:
    name: lidarr-postgres-secret
  monitoring:
    enablePodMonitor: true