apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: lidarr-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:ilNrO142,iv:wkAr/4jbCWR6hmyPTYkdtwlEJfRby0JjM/Ufb0nXJZA=,tag:hgYEcOF7gFcPDftnOjsrxg==,type:str]
    password: ENC[AES256_GCM,data:tFBd5G5rgHgtgMgbbR45Iv03zgI=,iv:GRID3Db5afhz2ZyfDlUjNVkjv76fN5oR6gyAAJvDjtE=,tag:sq8YZq8Zgtr7ee91RauSmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWXhJd2xIU0V0VTZCWTBT
            Y3RkQ0psM1NKN2I0QU55dDNXbkd5bnkyNEQ4CkllV2t3aXgrM2JTRERVcWFOVEhD
            V2dvWDhmWHVWL3FpdUNGWFRVNVlTbUEKLS0tIHlpcnhLWnZjbTNkRkk5YXVkL3Qy
            MVlNM2NzMnhuY3E3bTk4aklCNU5KVkUKRTV5HJ+Wxfti+lBoWts7AeJogsFa4vLW
            VYcawBFwre1HV6zGkfg3XY1JjE/ZWLXIJZIz9b5Bk+T+rGbbtUKN3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T19:58:37Z"
    mac: ENC[AES256_GCM,data:/3j+k8KEjwicU7sVP6mHQY5XRPXZkhQXvQopH4tkKSAGqp1kSmIDE4sRdDzNpLTfpAk+AFb8LWFny2ivyg9E9OVK4tN5REDOUyIJaqHHmHbTs1PKRgaRjL/AX1puyoVtcDd1BePLMImzXI5CdXw307xlXn3gueheXCrH2s5MIbQ=,iv:c4QPsbEjLcVD4ZBpUClGB2B8HBR2fFXpkPgph4qiIOo=,tag:9bmX1rNAOpD9r+Bx1gcV2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0