apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-pv-data