apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: radarr-postgres
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14
  storage:
    storageClass: nfs-client
    size: 1Gi
  bootstrap:
    initdb:
      database: radarr
      owner: radarr
      secret:
        name: radarr-postgres-secret
      postInitSQL:
        - CREATE DATABASE "radarr-log" OWNER radarr;
  superuserSecret:
    name: radarr-postgres-secret
  monitoring:
    enablePodMonitor: true
