apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: radarr-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:Gl38mJqW,iv:MIz2Rbdct/j7PlrriuPld38scVqPJ8ZS9JTB71+4Db4=,tag:bUrB8D3e7BlSqFFwEMWsig==,type:str]
    password: ENC[AES256_GCM,data:2I1TvB2TYsXLdKrHS1W8uZH6bdI=,iv:pptcM52V+OvMGCN6JiS7pApb6HOsAp2cj3lVTyqqcmQ=,tag:4UMROxGiUt6rWBNA7DYLZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eHV6WnlKQ1JNTVlFMlFn
            N0lCazVSbWhZV2lQVDZNbUZXcm1XTzYyTnkwCjdGcFFacmY1eHA5YnViVHQ2RmJm
            NUt2RWtEbTV5dUdSSE9iZ3lURTJMc1kKLS0tIFpFbjdVbmlYZ0pPUmhiTnFQOGNk
            QWJvNHlqSG5OM2RONysrS3lNcktzZFkK9ZxdV0cmtROmROWF+6HMcZYs0m/X7b8U
            Z2AHgiHokwEx3dfrE3Hr1MIIFVWp349QavmEb6AEIU7pVB7lveFnYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T20:51:54Z"
    mac: ENC[AES256_GCM,data:YHtUHg3c8A9N5DztwmindePhSVNU/nY8rGdJOhI5UqpSSW7lsqS1IjJ+7hVVJO2482KPe6qVjwyafvE3oNgsLH+L3GjIBMUhgtPCkCrPVe0zYdlezaXSf0UcDvJXcW/rhAEA9crQY5kvw9wkiw9VD8E3gJb7eR+yqSThGwXquBY=,iv:mDFDvMG1UzYQjucDA3p1oKQPF7gef7oDSd6vhRnRXyE=,tag:DdaHA52kv+XqOcCqtaSyqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0