apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app tasmo
  annotations:
    {}
  labels:
    app: *app
  namespace: default
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - imagePullPolicy: Always
          name: *app
          volumeMounts:
            - name: nfs-conf
              mountPath: /data
              subPath: tasmo/config
          image: ghcr.io/tasmoadmin/tasmoadmin@sha256:9d0869cb47d7d525f69ca555708c00b52dd899acc02e4d3e268bd949e29bb6fd
          # envFrom:
          #   - prefix: ''
          #     configMapRef:
          #       name: tasmo
          #       optional: false              
      hostNetwork: true
      restartPolicy: Always
      volumes:
        - name: nfs-conf
          persistentVolumeClaim: 
            claimName: nfs-pvc-containerdata 
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
