apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: decrypt
  namespace: flux-system
spec:
  # other fields...
  decryption:
    provider: sops
    secretRef:
      name: sops-age
