apiVersion: v1
kind: Service
metadata:
  name: &app watchstate
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector: 
    app: *app
  ports:
    - name: ws-tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.10.100.87
