apiVersion: v1
kind: Service
metadata:
  name: watchstate
  namespace: default
spec:
  selector: 
    app: watchstate
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: watchstatelb
#   namespace: default
#   annotations:
#     metallb.universe.tf/address-pool: default
# spec:
#   selector: 
#     app: watchstate
#   ports:
#     - name: ws-tcp-8080
#       port: 8080
#       protocol: TCP
#       targetPort: 8080
#   type: LoadBalancer
#   loadBalancerIP: 10.10.100.87
