apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app watchstate
  annotations:
    {}
  labels:
    app: *app
  namespace: default
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - imagePullPolicy: Always
          name: *app
          volumeMounts:
            - name: nfs-conf
              mountPath: /config
              subPath: watchstate/
          image: ghcr.io/arabcoders/watchstate:latest@sha256:9999a384d4ead0d3615e156c97243583d4ae2f3083d61ffe968334b96eca1459
          envFrom:
            - prefix: ''
              configMapRef:
                name: watchstate
                optional: false               
      restartPolicy: Always
      volumes:
        - name: nfs-conf
          persistentVolumeClaim: 
            claimName: nfs-pvc-containerdata
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate

