apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app watchstate
  annotations:
    {}
  labels:
    app: *app
  namespace: default
spec:
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - imagePullPolicy: Always
          name: *app
          volumeMounts:
            - name: nfs-conf
              mountPath: /config
              subPath: watchstate/
          image: ghcr.io/arabcoders/watchstate:latest@sha256:15a9ddee901f26446eae23dfcfa5bfe0a70adee02b760020a4c8a77c5fece65e
          envFrom:
            - prefix: ''
              configMapRef:
                name: watchstate
                optional: false               
      restartPolicy: Always
      volumes:
        - name: nfs-conf
          persistentVolumeClaim: 
            claimName: nfs-pvc-containerdata
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate

