apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name tls.netbootxyz
  namespace: default
spec:
  dnsNames:
    - netbootxyz.d90.name
  secretName: *name
  privateKey:
    algorithm: ECDSA
    size: 256
  revisionHistoryLimit: 1
  issuerRef:
    name: le-prod-issuer
    kind: ClusterIssuer
