apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- secret.sops.yaml
- status-deployment.yaml
- status-service.yaml
- tls.yaml
configMapGenerator:
- name: rtunnel-status
  files:
  - status.py
