apiVersion: v1
kind: Service
metadata:
  name: rtunnel-netmon
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rtunnel
  ports:
    - { name: http, port: 80, targetPort: 8090, protocol: TCP }
