apiVersion: v1
kind: Secret
metadata:
    name: rtunnel-ssh
    namespace: default
type: Opaque
stringData:
    rusys: ENC[AES256_GCM,data:OWmpQw0zMLU9yKtQJQgPnMFafMU17GS65wzeTOdNVWDh5xYFtEIbFR2muAuCLrecRoCwVyZyMrn/TZ2ijtLvj7MUaQVp+ZAsq13qN49+KsPOj/f+AnxlsEWBRLpi+rhgp485i9ZoCLQfIboC10m/bHBlDo/YxOH4HP3GGuJAeJlxo8xCLkr8rJUNh/8V9HamsF4PZvN4vcvffO9EljAV1KZJy3olbODTy3G+tC9I6WcYJ8Ztk6SBBgnsSH0j2dX1KEd1gYP4oExvPcIbdzOzeEP8Nm6qvHztX79iVHF6k4X2/fccH2Tj+RdE0Q087YYFWdwiRoUJd1hZX2KC82clo4ZWQQxOkl6qLgGf4DoYcxiaV4z3L6z6rgZx/vMUAHNzBTOOqfC6KcmTzbdRQUFsLvNmeb0zR8DAIQHpVf5y83e+aE/0/9RXrwBS4+y6iJvE6t3RUma/Q16AcTinEWXgcsCd85wHF2we2ahueDZ10UYlxifs73c/qhCvx0qLpuTLEWbGSC0k/xujCzIa/KlW,iv:v64bp0VV3VpjECeEZXmWrQwAcqIPwhYScq/0kApvA70=,tag:B0gHX13IJir0bo4F7ZDLLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTllsYU5nL3lvWmU2bFRa
            Ujlmc3kzZ0Z5MjF1MEM5bnBJWXRSSmVjUVZJCnM4d1psdnRXWnExOWk2RWJXeGRz
            S080SWpJTkM1QW5rbTRuWHBHWC9nWFEKLS0tIHN0MlR2bnp6c1NHd3c0MGg5QXBi
            dFlQSGdHU2Vma3hVQ004ZnA2SWVGMlEKq5uQ5Y17SgJGFhRyFbKplAHTYw/rX8zs
            MtCqqGH7isVBU4UMYpr8WE5PYm3KmTVw97ZmzZZG3ROcz8r1JSu6hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T15:18:46Z"
    mac: ENC[AES256_GCM,data:3InbF212DFbAlZE7UHlRJJeXZzfmCAzASIvzYZwad1eAA8rnY602NcGgoQ2nd3CwWM4806AnPNvxK9l/3djIobCyO4Rk4eZpArCRMchrvN5W/UbtziLcarKFYXQ6GVDXa4CHOkgOiwGTh+WgRk5Fp7Nb/mcQt9VlUkuzwzKQZKA=,iv:lRMpuqHnl6BMj5wCKbRwdgkQn1C81BT6UHLOJg1aT7Y=,tag:lD8a9NxtVQPn5sInz8wvnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
