apiVersion: v1
kind: Service
metadata:
  name: rtunnel-status
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rtunnel-status
  ports:
    - { name: http, port: 80, targetPort: 8080, protocol: TCP }
