apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs-pv-data-tdarr.yaml
  - nfs-pv-containerdata-tdarr.yaml
  - nfs-pvc-containerdata-tdarr.yaml
  - nfs-pvc-data-tdarr.yaml
  