apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-containerdata-tdarr
  namespace: tdarr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-pv-containerdata-tdarr
