apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls.capacitor
  namespace: flux-system
spec:
  dnsNames:
    - capacitor.d90.name
  secretName: tls.capacitor
  privateKey:
    algorithm: ECDSA
    size: 256
  revisionHistoryLimit: 1
  issuerRef:
    name: le-prod-issuer
    kind: ClusterIssuer
