apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  namespace: tdarr
  labels:
    app: tdarr
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      containers:
      - name: tdarr
        image: ghcr.io/haveagitgat/tdarr:2.50.01@sha256:67d6a456d3c7963d2bc50318275843015af76e1f4dced3b1c5a91f8874d230bf
        env:
          - name: NODE_ENV
            value: "production"
        volumeMounts:
          - name: nfs-data
            mountPath: /data
          - name: nfs-conf
            mountPath: /app/server
            subPath: tdarr/server
          - name: nfs-conf
            mountPath: /app/configs
            subPath: tdarr/configs
          - name: nfs-conf
            mountPath: /app/logs
            subPath: tdarr/logs
          - name: nfs-conf
            mountPath: /temp
            subPath: tdarr/transcode_cache
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nfs-pvc-data-tdarr
        - name: nfs-conf
          persistentVolumeClaim:
            claimName: nfs-pvc-containerdata-tdarr
