apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-unbound
  namespace: traefik-unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-unbound
  template:
    metadata:
      labels:
        app: traefik-unbound
    spec:
      serviceAccountName: traefik-unbound
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: manager
          image: ghcr.io/d90/traefik-to-opnsense-unbound:1.0.0@sha256:7702c82e188eb88de6411f03a91e146e00acc9cb5ed9a2c48b1948ecf22df85c
          env:
            - name: OPNSENSE_URL
              value: "https://10.10.10.1"
            - name: TARGET_IP
              value: "10.10.100.101"
            - name: TLS_SKIP_VERIFY
              value: "true"
            - name: OPNSENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: opnsense-creds
                  key: api-key
            - name: OPNSENSE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: opnsense-creds
                  key: api-secret
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
