apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-vip
  - namespaces
  - cert-manager
  - housekeeping
  # - kustomization
  - reloader
  - storage
  - system-upgrade
  - vgpu
