apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: prowlarr-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:JT1mgJfmJkA=,iv:Yly5gm6B0lktDite1T9vQHzKgGAq3UbV6024eLPnTkc=,tag:TyrXM95uBfLes9lifwEByg==,type:str]
    password: ENC[AES256_GCM,data:9+veeasWd0Wx/XiI/7Ap0DDqwas=,iv:rAssIHGirbXBsCoEkuIwPQSBCQ/OA7k+36PyJWHq+3c=,tag:/xA1+63FZYnBwoM2c/Fh/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT2VTU0ZBdDRucGNKTmVo
            YWpxaHBxQzdHRVpzN0RKOEs3Q0p2cUlnRVRrCmdvY1g3bDRGRFV5eHNHZldFZkhq
            MG52NjNrc3VuQ3VqQmRaMW90MnJDbFEKLS0tICtDMVJ0Rjk1dFI4QkRvcFRhRWVI
            dFhpUkFmeGR5VkloZkIrU0JubVlLZmsKQgjDwdW7H7iP5TUmn+E0OAYsmuWsVDFA
            lXSCG+6awqWoDpo1tZIck/GLrySe0zVL9IHe3/5QvlFrTfgeHT5Z7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T02:42:42Z"
    mac: ENC[AES256_GCM,data:GaZKAMiGEgZO62n/k8DDXFG0VtcZu69VQiVe8AtVTxQvp8ubZJaKnDJVeTe+cEPeXt2t67As9K0Y6hXK07chMYj7PXL6E4FV1m+e3qzD8AQLxCYT6hjSyM9zx0MB9JPAzWt7HqJbEvKYJiHPyasyFXb8YHxYCltE1MuY1vYNSoA=,iv:ExRkHHXWgv3F4v2QwM0KYtQQ6pTHiS/Oy2Sk0z0pcvs=,tag:z5JKqJ4XoDM9fn/TsKzRDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0