apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-10.10.100.86"
    metallb.universe.tf/address-pool: first-pool
spec:
  selector: 
    app.kubernetes.io/instance: una
    app.kubernetes.io/name: unifi
  ports:
    - name: uni-tcp-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: uni-tcp-8843
      port: 8843
      protocol: TCP
      targetPort: 8843
    - name: uni-tcp-8880
      port: 8880
      protocol: TCP
      targetPort: 8880
    - name: uni-tcp-6789
      port: 6789
      protocol: TCP
      targetPort: 6789
    - name: uni-tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  # type: ClusterIP
  type: LoadBalancer
  loadBalancerIP: 10.10.100.86

---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
  namespace: default
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-10.10.100.86"
    metallb.universe.tf/address-pool: first-pool
spec:
  selector: 
    app.kubernetes.io/instance: una
    app.kubernetes.io/name: unifi
  ports: 
    - name: uni-udp-3478
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: uni-udp-10001
      port: 10001
      protocol: UDP
      targetPort: 10001
    - name: uni-udp-5514
      port: 5514
      protocol: UDP
      targetPort: 5514
    - name: uni-udp-1900
      port: 1900
      protocol: UDP
      targetPort: 1900
  # type: ClusterIP
  type: LoadBalancer
  loadBalancerIP: 10.10.100.86
