apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: homebox-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:XEiFJkXpwg==,iv:BITzq9oGYsrRqrykwDQZIu7l5jfCgFDuIVRDsx9Rt6I=,tag:D+Rrk8CCqrQPghtUzchFPw==,type:str]
    password: ENC[AES256_GCM,data:XwpjgSPgg2BF4V27ocu8xV1KUXMLscBuEQu1HbAZTDA=,iv:4St23DvvEaY0HJPo3z2cNRjacpUV73qnh29tw9SqsNo=,tag:SCfCL5XSo0V8IunR7evyqg==,type:str]
    api_key_pepper: ENC[AES256_GCM,data:ql2CTbsdzXoH5qGqy4fGeyU/VTxmj25tcV6zGEejcdXlQwcdvDBIff0mqdeEqqoMlIaSm5JEaz8+ccAdZMA2oA==,iv:wkoagTa8Y5r9S+Ar7d/E+PDOE7fGF7OuK+th8C4HvUI=,tag:GZRf56kvmyFe5XRSVCAX2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQS9mTlQwTHVsZEwrYTFU
            UW5pZTFtK0FQT1VWTEJnOGFpVmFzTGdObTEwCjVkdnZvK2V3dDVyZ09oUVE1RGVn
            NmREUk5PTU5zdmluNnYvcFdTanJIVnMKLS0tIDMrT0RLcEhTM0VKR0dsNWZnL1RF
            dWUwcFkzVDFEWlJsdXhtN1djNDdEVUkKLG534xVmP/PlYIlQHSIYFN88TA5aZJgg
            LzVPc5jvPH911gspPGF+epzlq1My6L+XxOik7l+pjaHTf58nvYvVbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T16:00:10Z"
    mac: ENC[AES256_GCM,data:inrgLhMyA9p4HcRk9OW8OgaL1Fv+uXsHYGaOHqeaAnIdy5BgccF2yerKvdZbTKpQtzvbOeoi0lbuTF6ucRB25LBZz9McXOKDJcdqS68og91lPhYldRVEeB49QKNS0RpIELUTg9+lSMvZ68T+BgeTAAIhLixffhvpGpJ5/xCO2rI=,iv:j/6nWtCObg9ENFBvypQ4iqjBg3JxUJslKRhbtY3qYmc=,tag:nnmlx/RKYITDW6o0CwxNXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
