apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: seerr-postgres-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:tYUiw3U=,iv:iqjqeYodp6o30kNHdFA51x0LqJd7qR6RwkplET6y9j8=,tag:QYDxLgXeGvmbOo8UAw7hjQ==,type:str]
    password: ENC[AES256_GCM,data:mN7Hpl03gCAo3dr/Fd9unsASaF8=,iv:bPIxVRUNaT2MbwQyjnyi/iY9c/LHFp14BKwbIBt56hk=,tag:3WNWeN1Sm8O3eBC/4JSMHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qvmjlpa0m679rfgw5p00gpy25c3gan3pg4ad56x4z3g2mhqguf2s2dsy7u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RlR5Q3pMTitmaG8vak14
            ZFZ2REFGYVVqc2dudVJwNjR0eS8zcEVMMXhVCmJXdS9MVUlzelhsSWt0dkNjQVB3
            YTRmb2RzY1E2R2tFdklDSTNWNWFNZkUKLS0tIFh1a0dTSzNqVWt1cHUyUng0Sllk
            QU5xZEJSSE9oQ1Exa3N2a204L3VPZFUK7vZhCYazSd/MWBsBGtOin302/D+moV0R
            elff/Yvbhd0VB7ORtxdrqVjjIuIaSHIPiUqephwCxRlQmrfCOcLfnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T20:46:07Z"
    mac: ENC[AES256_GCM,data:DxqQFOlSnbT2PX7isBcrxy+6Doq3YDOuuktZREkf5oJmGTGEYTUPAremRw4DRZvifJN1+qEdFLcfgNcDTRqSw050r5L3FlsABXgm5AdS+9RvsMJsbG4lDbIE5Um2hB/SqXlAazqvCpza3ayxnMs6r+/CbLS/sTsIJBjL6jc3fnE=,iv:1xHYUghYIaMmUCd0apOzBc/397iw+tkfUpgH/Ig7C4w=,tag:x8ECOElKjnbuxWCMkzYRrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0