apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bazarr
- configmaps
- cloudnative-pg
# - deluge
# - dynamic-dns
# - homepage-dashboard
# - homeassistant
# - jellyfin
# - lidarr
# - mosquitto
# - netbootxyz
- nzbget
# - profilarr
- prowlarr
- radarr
# - scrypted
# - seerr
- sonarr
# - tasmo
# - una
# - watchstate
# - webnettools
