apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bazarr
- configMap
- cloudNativePG
- deluge
- dynamicDNS
- homepage-dashboard
- homeassistant
# - jellyfin
- lidarr
- mosquitto
- netbootxyz
- nzbget
- ohif
- profilarr
- prowlarr
- radarr
- scrypted
- seerr
- sonarr
- tasmo
# - una
# - watchstate
- webnettools
